#this is just a simple makefile. no real need to add anything here

all: ./
	g++ -std=c++11 -g ./Example.cpp -o Example -I../include -L../bin/ -lWindowAPI_D -lGLU -lGL -lX11 -lpthread -lstdc++ 2> errors.txt
