Foundation window management API: FWindow::FWindow
ColourBits
ContextCreated
CurrentState
CurrentSwapInterval
CurrentWindowStyle
DepthBits
DestroyedEvent
DisableDecorator
EnableDecorator
EXTSwapControlSupported
Focus
FocusEvent
FullScreen
FWindow
GetContextHasBeenCreated
GetCurrentState
GetInFocus
GetIsCurrentContext
GetIsFullScreen
GetIsMaximized
GetIsMinimized
GetKeyState
GetMousePosition
GetMousePosition
GetOpenGLExtensions
GetOpenGLVersion
GetPosition
GetPosition
GetResolution
GetResolution
GetShouldClose
GetWindowName
ID
InFocus
InitGLExtensions
Initialize
Initialized
InitializeEvents
InitializeGL
IsCurrentContext
KeyEvent
Keys
MakeCurrentContext
Maximize
MaximizedEvent
MESASwapControlSupported
Minimize
MinimizedEvent
MouseButton
MouseButtonEvent
MouseMoveEvent
MousePosition
MouseWheelEvent
MovedEvent
Name
Position
PrintOpenGLExtensions
PrintOpenGLVersion
ResizeEvent
Resolution
Restore
SetCurrentState
SetIcon
SetMousePosition
SetOnDestroyed
SetOnFocus
SetOnKeyEvent
SetOnMaximized
SetOnMinimized
SetOnMouseButtonEvent
SetOnMouseMove
SetOnMouseWheelEvent
SetOnMoved
SetOnResize
SetPosition
SetResolution
SetStyle
SetSwapInterval
SetTitleBar
SGISwapControlSupported
ShouldClose
Shutdown
StencilBits
SwapDrawBuffers
WindowManager
~FWindow
FWindow::FWindow (const char * WindowName, GLuint Width = 1280, GLuint Height = 720, GLuint ColourBits = 8, GLuint DepthBits = 24, GLuint StencilBits = 8)
Constructor.
Author
Ziyad Barakat
Date
29/11/2014
Parameters
WindowName Name of the window.
Width The width.
Height The height.
ColourBits The colour bits.
DepthBits The depth bits.
StencilBits The stencil bits.
Definition at line 31 of file Window.cpp.
References ContextCreated, CurrentState, ERROR_INVALIDWINDOWNAME, EXTSwapControlSupported, InitializeEvents(), IsCurrentContext, IsValidString(), MESASwapControlSupported, Position, PrintErrorMessage(), Resolution, SGISwapControlSupported, ShouldClose, and WINDOWSTATE_NORMAL.
                           :
     Name(WindowName),
     ColourBits(ColourBits),
     DepthBits(DepthBits),
     StencilBits(StencilBits)
 {
     Resolution[0] = Width;
     Resolution[1] = Height;
     Position[0] = 0;
     Position[1] = 0;
     ShouldClose = GL_FALSE;
     EXTSwapControlSupported = GL_FALSE;
     SGISwapControlSupported = GL_FALSE;
     MESASwapControlSupported = GL_FALSE;
     if(!IsValidString(WindowName))
     {
         PrintErrorMessage(ERROR_INVALIDWINDOWNAME);
         exit(0);
     }
     InitializeEvents();
     CurrentState = WINDOWSTATE_NORMAL;
     ContextCreated = GL_FALSE;
     IsCurrentContext = GL_FALSE;
 }