Foundation window management API: main
main
OnWindowKeyPressed
int main ()
Main entry-point for this application.
Author
Ziyad
Date
29/11/2014
Returns
Exit-code for the process - 0 for success, else an error code.
Definition at line 40 of file Example.cpp.
References WindowManager::AddWindow(), DECORATOR_MINIMIZEBUTTON, WindowManager::EnableWindowDecorator(), WindowManager::GetNumWindows(), WindowManager::GetWindowByIndex(), WindowManager::GetWindowShouldClose(), WindowManager::Initialize(), FWindow::MakeCurrentContext(), OnWindowKeyPressed(), WindowManager::PollForEvents(), WindowManager::SetWindowOnKeyEvent(), WindowManager::SetWindowStyle(), WindowManager::ShutDown(), FWindow::SwapDrawBuffers(), and WINDOWSTYLE_BARE.
 {
     WindowManager::Initialize();
     WindowManager::AddWindow(new FWindow("Example"));//->AddWindow(new FWindow("Example2"));
     WindowManager::SetWindowOnKeyEvent("Example", &OnWindowKeyPressed);
     WindowManager::SetWindowStyle("Example", WINDOWSTYLE_BARE);
     WindowManager::EnableWindowDecorator("Example", DECORATOR_MINIMIZEBUTTON);
     while (!WindowManager::GetWindowShouldClose("Example"))
     {
         WindowManager::PollForEvents();
         for (GLuint i = 0; i < WindowManager::GetNumWindows(); i++)
         {
             WindowManager::GetWindowByIndex(i)->MakeCurrentContext();
             glClearColor(0.25f, 0.25f, 0.25f, 0.25f);
             glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
             WindowManager::GetWindowByIndex(i)->SwapDrawBuffers();
         }
     }
     WindowManager::ShutDown();
     return 0;
 }