Foundation window management API: PrintErrorMessage
DECORATOR_BORDER
DECORATOR_CLOSEBUTTON
DECORATOR_HORIZONTALSCROLLBAR
DECORATOR_ICON
DECORATOR_MAXIMIZEBUTTON
DECORATOR_MINIMIZEBUTTON
DECORATOR_SIZEABLEBORDER
DECORATOR_TITLEBAR
DECORATOR_VERTICALSCROLLBAR
ERROR_ALREADYINITIALIZED
ERROR_EXISTINGCONTEXT
ERROR_FUNCTIONNOTIMPLEMENTED
ERROR_INVALIDCONTEXT
ERROR_INVALIDEVENT
ERROR_INVALIDRESOLUTION
ERROR_INVALIDTITLEBAR
ERROR_INVALIDWINDOW
ERROR_INVALIDWINDOWINDEX
ERROR_INVALIDWINDOWNAME
ERROR_INVALIDWINDOWSTATE
ERROR_INVALIDWINDOWSTYLE
ERROR_LINUX_CANNOTCONNECTXSERVER
ERROR_LINUX_CANNOTCREATEWINDOW
ERROR_LINUX_FUNCTIONNOTIMPLEMENTED
ERROR_LINUX_INVALIDVISUALINFO
ERROR_NOCONTEXT
ERROR_NOTINITIALIZED
ERROR_WINDOWNOTFOUND
ERROR_WINDOWS_CANNOTCREATEWINDOW
ERROR_WINDOWS_CANNOTINITIALIZE
ERROR_WINDOWS_FUNCTIONNOTIMPLEMENTED
FOUNDATION_ERROR
FOUNDATION_OKAY
IsValidDestroyedEvent
IsValidFocusEvent
IsValidKeyEvent
IsValidMouseMoveEvent
IsValidMouseWheelEvent
IsValidMovedEvent
IsValidString
KEY_ARROW_DOWN
KEY_ARROW_LEFT
KEY_ARROW_RIGHT
KEY_ARROW_UP
KEY_BACKSPACE
KEY_CAPSLOCK
KEY_DELETE
KEY_END
KEY_ENTER
KEY_ERROR
KEY_ESCAPE
KEY_F1
KEY_F10
KEY_F11
KEY_F12
KEY_F2
KEY_F3
KEY_F4
KEY_F5
KEY_F6
KEY_F7
KEY_F8
KEY_F9
KEY_FIRST
KEY_HOME
KEY_INSERT
KEY_KEYPAD_0
KEY_KEYPAD_1
KEY_KEYPAD_2
KEY_KEYPAD_3
KEY_KEYPAD_4
KEY_KEYPAD_5
KEY_KEYPAD_6
KEY_KEYPAD_7
KEY_KEYPAD_8
KEY_KEYPAD_9
KEY_KEYPAD_ADD
KEY_KEYPAD_DIVIDE
KEY_KEYPAD_ENTER
KEY_KEYPAD_MULTIPLY
KEY_KEYPAD_PERIOD
KEY_KEYPAD_SUBTRACT
KEY_LAST
KEY_LEFTALT
KEY_LEFTCONTROL
KEY_LEFTSHIFT
KEY_LEFTWINDOW
KEY_NUMLOCK
KEY_PAGEDOWN
KEY_PAGEUP
KEY_PAUSE
KEY_PRINTSCREEN
KEY_RIGHTALT
KEY_RIGHTCONTROL
KEY_RIGHTSHIFT
KEY_RIGHTWINDOW
KEY_SCROLLLOCK
KEY_TAB
KEYSTATE_DOWN
KEYSTATE_UP
LINUX_DECORATOR
LINUX_DECORATOR_BORDER
LINUX_DECORATOR_CLOSE
LINUX_DECORATOR_MAXIMIZE
LINUX_DECORATOR_MINIMIZE
LINUX_DECORATOR_MOVE
LINUX_FUNCTION
MOUSE_BUTTONDOWN
MOUSE_BUTTONUP
MOUSE_LAST
MOUSE_LEFTBUTTON
MOUSE_MIDDLEBUTTON
MOUSE_RIGHTBUTTON
MOUSE_SCROLL_DOWN
MOUSE_SCROLL_UP
OnDestroyedEvent
OnFocusEvent
OnKeyEvent
OnMaximizedEvent
OnMinimizedEvent
OnMouseButtonEvent
OnMouseMoveEvent
OnMouseWheelEvent
OnMovedEvent
OnResizeEvent
PrintErrorMessage
PrintWarningMessage
WARNING_NOGLEXTENSIONS
WARNING_NOTCURRENTCONTEXT
WINDOWSTATE_FULLSCREEN
WINDOWSTATE_MAXIMIZED
WINDOWSTATE_MINIMIZED
WINDOWSTATE_NORMAL
WINDOWSTYLE_BARE
WINDOWSTYLE_DEFAULT
WINDOWSTYLE_POPUP
static void PrintErrorMessage (GLuint ErrorNumber) static
Definition at line 242 of file WindowAPI_Defs.h.
References ERROR_ALREADYINITIALIZED, ERROR_EXISTINGCONTEXT, ERROR_FUNCTIONNOTIMPLEMENTED, ERROR_INVALIDCONTEXT, ERROR_INVALIDEVENT, ERROR_INVALIDRESOLUTION, ERROR_INVALIDTITLEBAR, ERROR_INVALIDWINDOW, ERROR_INVALIDWINDOWINDEX, ERROR_INVALIDWINDOWNAME, ERROR_INVALIDWINDOWSTATE, ERROR_INVALIDWINDOWSTYLE, ERROR_LINUX_CANNOTCONNECTXSERVER, ERROR_LINUX_CANNOTCREATEWINDOW, ERROR_LINUX_FUNCTIONNOTIMPLEMENTED, ERROR_LINUX_INVALIDVISUALINFO, ERROR_NOCONTEXT, ERROR_NOTINITIALIZED, ERROR_WINDOWNOTFOUND, ERROR_WINDOWS_CANNOTCREATEWINDOW, and ERROR_WINDOWS_FUNCTIONNOTIMPLEMENTED.
Referenced by WindowManager::AddWindow(), FWindow::DisableDecorator(), WindowManager::DoesExist(), FWindow::EnableDecorator(), FWindow::Focus(), FWindow::FullScreen(), FWindow::FWindow(), FWindow::GetIsCurrentContext(), FWindow::GetIsFullScreen(), FWindow::GetMousePosition(), WindowManager::GetMousePositionInScreen(), WindowManager::GetMousePositionInWindow(), WindowManager::GetNumWindows(), FWindow::GetOpenGLExtensions(), FWindow::GetOpenGLVersion(), FWindow::GetPosition(), FWindow::GetResolution(), WindowManager::GetScreenResolution(), WindowManager::GetWindowByIndex(), WindowManager::GetWindowByName(), FWindow::GetWindowName(), WindowManager::GetWindowResolution(), FWindow::MakeCurrentContext(), FWindow::Maximize(), WindowManager::PollForEvents(), FWindow::PrintOpenGLExtensions(), FWindow::PrintOpenGLVersion(), FWindow::Restore(), FWindow::SetCurrentState(), FWindow::SetMousePosition(), FWindow::SetOnDestroyed(), FWindow::SetOnFocus(), FWindow::SetOnMaximized(), FWindow::SetOnMinimized(), FWindow::SetOnMouseButtonEvent(), FWindow::SetOnMouseMove(), FWindow::SetOnMouseWheelEvent(), FWindow::SetOnMoved(), FWindow::SetOnResize(), FWindow::SetPosition(), FWindow::SetResolution(), FWindow::SetStyle(), FWindow::SetSwapInterval(), FWindow::SetTitleBar(), FWindow::Shutdown(), and FWindow::SwapDrawBuffers().
 {
     switch(ErrorNumber)
     {
         case ERROR_NOCONTEXT:
         {
             printf("Error: An OpenGL context must first be created(initialize the window) \n");
             break;
         }
         case ERROR_INVALIDWINDOWNAME:
         {
             printf("Error: invald window name \n");
             break;
         }
         case ERROR_INVALIDWINDOWINDEX:
         {
             printf("Error: invalid window index \n");
             break;
         }
         case ERROR_INVALIDWINDOWSTATE:
         {
             printf("Error: invalid window state \n");
             break;
         }
         case ERROR_INVALIDRESOLUTION:
         {
             printf("Error: invalid resolution \n");
             break;
         }
         case ERROR_INVALIDCONTEXT:
         {
             printf("Error: Failed to create OpenGL context \n");
             break;
         }
         case ERROR_EXISTINGCONTEXT:
         {
             printf("Error: context already created \n");
             break;
         }
         case ERROR_NOTINITIALIZED:
         {
             printf("Error: Window manager not initialized \n");
             break;
         }
         case ERROR_ALREADYINITIALIZED:
         {
             printf("Error: window has already been initialized \n");
             break;
         }
         case ERROR_INVALIDTITLEBAR:
         {
             printf("Error: invalid title bar name (cannot be null or nullptr) \n");
             break;
         }
         case ERROR_INVALIDEVENT:
         {
             printf("Error: invalid event callback given \n");
             break;
         }
         case ERROR_WINDOWNOTFOUND:
         {
             printf("Error: window was not found \n");
             break;
         }
         case ERROR_INVALIDWINDOWSTYLE:
         {
             printf("Error: invalid window style given \n");
             break;
         }
         case ERROR_INVALIDWINDOW:
         {
             printf("Error: invalid window given \n");
             break;
         }
         case ERROR_FUNCTIONNOTIMPLEMENTED:
         {
             printf("Error: I'm sorry but this function has not been implemented yet :( \n");
             break;
         }
         case ERROR_LINUX_CANNOTCONNECTXSERVER:
         {
             printf("Error: cannot connect to X server \n");
             break;
         }
         case ERROR_LINUX_INVALIDVISUALINFO:
         {
             printf("Error: Invalid visual information given \n");
             break;
         }
         case ERROR_LINUX_CANNOTCREATEWINDOW:
         {
             printf("Error: failed to create window \n");
             break;
         }
         case ERROR_LINUX_FUNCTIONNOTIMPLEMENTED:
         {
             printf("Error: function not implemented on linux platform yet. sorry :( \n");
             break;
         }
         case ERROR_WINDOWS_CANNOTCREATEWINDOW:
         {
             printf("Error: failed to create window \n");
             break;
         }
         case ERROR_WINDOWS_FUNCTIONNOTIMPLEMENTED:
         {
             printf("Error: function not implemented on Windows platform yet. sorry ;( \n");
             break;
         }
         default:
         {
             printf("Error: unspecified Error \n");
             break;
         }
     }
 }